services:
  app: &app
    build:
      context: .
      dockerfile: Dockerfile
    command: echo "Disabled by default"
    volumes:
      - .:/var/www/app

  server:
    <<: *app
    command: flask --app hackaton run --debug --host 0.0.0.0
    ports:
      - 5000:5000

  client:
    <<: *app
    command: bash -c "cd client && npm run dev -- --host 0.0.0.0"
    ports:
      - 5173:5173
