services:
  app: &app
    build:
      context: .
      dockerfile: Dockerfile
    command: echo "Disabled by default"
    environment:
      - FLASK_APP=hackaton
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/hackaton?sslmode=disable&gssencmode=disable
      - LOBO_GUARA_KEY=OlnuoKHJcXZJD0-t7aFAVCEz3mp8l45-1k0m7ykShn4=
      - SECRET_KEY=3bf99d04a9b2af6a3afbfbce344f79de
    volumes:
      - .:/var/www/app

  server:
    <<: *app
    command: flask --app hackaton run --debug --host 0.0.0.0
    ports:
      - 7777:5000
    depends_on:
      - database

  client:
    <<: *app
    command: bash -c "cd client && pnpm run dev --host 0.0.0.0"
    ports:
      - 5173:5173

  database:
    image: postgres:17.2-alpine3.20
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres-data:
