"""Encrypt credentials password

Revision ID: 5bc6dc220cca
Revises: d06ebcf71c05
Create Date: 2024-11-23 18:46:24.898001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bc6dc220cca'
down_revision = 'd06ebcf71c05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_salt', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('password_encrypted', sa.LargeBinary(), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('password_encrypted')
        batch_op.drop_column('password_salt')

    # ### end Alembic commands ###
