"""Encrypt credentials otp_key

Revision ID: 69c511acfc6f
Revises: 5bc6dc220cca
Create Date: 2024-11-23 19:07:27.697388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69c511acfc6f'
down_revision = '5bc6dc220cca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_key_salt', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('otp_key_encrypted', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('otp_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_key', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('otp_key_encrypted')
        batch_op.drop_column('otp_key_salt')

    # ### end Alembic commands ###
