"""Add ON DELETE CASCADE to password_tags

Revision ID: f324fbecb9c5
Revises: 69c511acfc6f
Create Date: 2024-11-23 19:23:42.405555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f324fbecb9c5'
down_revision = '69c511acfc6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credential_tags', schema=None) as batch_op:
        batch_op.drop_constraint('credential_tags_credential_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('credential_tags_tag_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'credentials', ['credential_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credential_tags', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('credential_tags_tag_id_fkey', 'tags', ['tag_id'], ['id'])
        batch_op.create_foreign_key('credential_tags_credential_id_fkey', 'credentials', ['credential_id'], ['id'])

    # ### end Alembic commands ###
